# Список поддерживаемых операций
LOAD_CONST = 'LOAD_CONST'
STORE_NAME = 'STORE_NAME'
LOAD_NAME = 'LOAD_NAME'
BINARY_ADD = 'BINARY_ADD'
RETURN_VALUE = 'RETURN_VALUE'
POP_JUMP_IF_FALSE = 'POP_JUMP_IF_FALSE'
JUMP_FORWARD = 'JUMP_FORWARD'
COMPARE_OP = "COMPARE_OP"
JUMP_BACKWARD = "JUMP_BACKWARD"
RAISE_EXCEPTION = "RAISE_EXCEPTION"
SETUP_EXCEPT = "SETUP_EXCEPT"
POP_BLOCK = "POP_BLOCK"
