createproject:
	python -m django startproject inventory .
runserver:
	python manage.py runserver
startapp:
	python manage.py startapp items
makemigrations:
	python manage.py makemigrations
migrate:
	python manage.py migrate
createsuperuser:
	python manage.py createsuperuser