version: '3.8'

services:
  web:
    image: my-fastapi-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      # Здесь можно добавить переменные окружения, если они нужны вашему приложению
      # Например:
      # ENV_VAR_NAME: value
    volumes:
      - .:/app
    restart: always